### ISSUE TITLE
Dodać naszego hamburgera z menu do activity_school_plan.xml  

### ISSUE THREAD

**Issue by moradewicz** [PWSZaplikacjamobilna/PWSZWloclawek#2]
kek
![image](https://cloud.githubusercontent.com/assets/9642287/21080442/8a95daee-bfaf-11e6-80d4-9f7fed6a3041.png)

**Comment by ekorpalski** [comment]
Heheh można dodac :D

**Comment by moradewicz** [comment]
to się nazywa hamburger chyba 
![image](https://cloud.githubusercontent.com/assets/9642287/21081684/ee5669a6-bfcb-11e6-9ff6-aee26dac2c7b.png)
